### ISSUE TITLE
Actions による PDF 自動更新により PR がコンフリクト状態になる問題

### ISSUE THREAD

**Issue by dynamis** [wot-jp-community/wot-architecture#196]
PR #187 によって Github Actions で index-with-links.html, index-with-links.pdf を自動生成、bot によるコミットを行うようにした。

その副作用として、何か index.html を書き換えるコミットを push (PR のマージ) すると index-with-links.pdf の書き換えコミットが自動で行われ、その時点以前に建てられた全ての PR が github.com (web ui) では resolve 不可能なコンフリクト状態になってしまい、PR マージ作業の手間が増えてしまっている。

具体的には以下の手順を git コマンドラインで実施する必要が生じている:

```sh
git clone https://github.com/wot-jp-community/wot-architecture.git
cd wot-architecture
# マージしたい PR のブランチ名を指定してマージ
# github.com 上の説明では origin/ なしで良さそうに書かれてるがそんなことはない
git merge --no-ff origin/dynamis-patch-NNN
# github.com 上の説明では書かれていないがコンフリクトの解決が必要:
git checkout --theirs index-with-links.pdf
git add index-with-links.pdf; git commit -m "ignore conflict of auto generated pdf"
# git push には Personal Access Tokens が必要なのでトークン生成してパスワードとして入力すること
# Token の発行はこちらで行える: https://github.com/settings/tokens (scope は repo だけで良い)
# 参考: https://docs.github.com/ja/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token
git push
```

面倒なのでこれはせずに済ませられるフローを作りたいがどうするのが良いか要検討。

- index-with-link.html と index-with-links.pdf の自動生成・コミットは index.html 更新時に常に行うのではなく手動でキックできるようにする？
- 自動コミットは index-with-link.html までにする？
- index-with-link.pdf はそもそもリポジトリに入れるのではなく releases に自動登録するようにする？

**Comment by kou029w** [comment]
デフォルトブランチとPRでのPDFの生成結果が衝突するということだと想像するのですが、PRではartifactsで済ませてコミットせず、コミットのためのトリガーはデフォルトブランチのみにしたほうが良いかもしれないですね。

**Comment by kou029w** [comment]
参考:
- [actions/upload\-artifact](https://github.com/actions/upload-artifact)

```yaml
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: index-with-link
          path: |
            index-with-link.html
            index-with-link.pdf
      - name: Commit
        if: github.ref == 'refs/heads/master'
        run: # ...
```
